# FROM node as builder
# COPY package.json package-lock.json ./
# RUN npm install --only=prod && mkdir /app && mv ./node_modules ./app
# WORKDIR /app
# COPY . .
# RUN npm run build

FROM nginx:alpine
COPY ./.nginx/nginx.conf /etc/nginx/nginx.conf
RUN rm -rf /usr/share/nginx/html/*
COPY /build /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
