version: '3'

services:
    server:
      build: server/
      restart: always
      ports:
        - 5000:5000

    client:
      build: client/
      restart: always
      ports:
        - 3000:3000



