version: '3'

volumes:
    mongodb_volume:

services:
  server:
    build: server/
    restart: always
    ports:
      - 5000:5000

  # nginx:
  #   build: client/
  #   restart: always
  #   ports:
  #     - 80:80

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_volume:/data/db
    restart: always
    container_name: mongo
    hostname: mongo
    ports:
      - 27017:27017
